language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
- DB=pgsql

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
    - php: 5.3
    - php: 5.4
    - php: 5.5
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache


before_install:
  - composer self-update
  - composer validate

install: travis_retry composer install --no-interaction --prefer-source


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
